import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google'; // apenas escrevendo o nome da font pode-se exportá-la
import { Content } from './content';

/*
* A depender da fonte deve-se passar objetos com as propriedades exigidas.
* Observe que definimos variable nas duas fontes, pois por meio disso faremos
* com que o tailwindcss carregue estas fontes passando-as como variáveis
*/
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-alt'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} font-sans`}>
        {/**
         * Costumo usar um componente Content em volta dos filhos do layout principal, pois
         * o componente layout é renderizado do lado do servidor e limita uso de estados dinâmicos
         * seja para troca de temas, uso de api context ou redux.
        */}
        <Content>
          {children}
        </Content>
      </body>
    </html>
  )
}
